// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fishjam/peer_notifications.proto
// Protobuf Java Version: 4.26.1

package fishjam;

public final class PeerNotifications {
  private PeerNotifications() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      PeerNotifications.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fishjam.PeerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
     * @return Whether the authenticated field is set.
     */
    boolean hasAuthenticated();
    /**
     * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
     * @return The authenticated.
     */
    fishjam.PeerNotifications.PeerMessage.Authenticated getAuthenticated();
    /**
     * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
     */
    fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder getAuthenticatedOrBuilder();

    /**
     * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
     * @return Whether the authRequest field is set.
     */
    boolean hasAuthRequest();
    /**
     * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
     * @return The authRequest.
     */
    fishjam.PeerNotifications.PeerMessage.AuthRequest getAuthRequest();
    /**
     * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
     */
    fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder getAuthRequestOrBuilder();

    /**
     * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
     * @return Whether the mediaEvent field is set.
     */
    boolean hasMediaEvent();
    /**
     * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
     * @return The mediaEvent.
     */
    fishjam.PeerNotifications.PeerMessage.MediaEvent getMediaEvent();
    /**
     * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
     */
    fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder getMediaEventOrBuilder();

    fishjam.PeerNotifications.PeerMessage.ContentCase getContentCase();
  }
  /**
   * <pre>
   * Defines any type of message sent between FJ and a peer
   * </pre>
   *
   * Protobuf type {@code fishjam.PeerMessage}
   */
  public static final class PeerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fishjam.PeerMessage)
      PeerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        PeerMessage.class.getName());
    }
    // Use PeerMessage.newBuilder() to construct.
    private PeerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PeerMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fishjam.PeerNotifications.PeerMessage.class, fishjam.PeerNotifications.PeerMessage.Builder.class);
    }

    public interface AuthenticatedOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fishjam.PeerMessage.Authenticated)
        com.google.protobuf.MessageOrBuilder {
    }
    /**
     * <pre>
     * Response sent by FJ, confirming successfull authentication
     * </pre>
     *
     * Protobuf type {@code fishjam.PeerMessage.Authenticated}
     */
    public static final class Authenticated extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:fishjam.PeerMessage.Authenticated)
        AuthenticatedOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          Authenticated.class.getName());
      }
      // Use Authenticated.newBuilder() to construct.
      private Authenticated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private Authenticated() {
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_Authenticated_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_Authenticated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.PeerNotifications.PeerMessage.Authenticated.class, fishjam.PeerNotifications.PeerMessage.Authenticated.Builder.class);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof fishjam.PeerNotifications.PeerMessage.Authenticated)) {
          return super.equals(obj);
        }
        fishjam.PeerNotifications.PeerMessage.Authenticated other = (fishjam.PeerNotifications.PeerMessage.Authenticated) obj;

        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static fishjam.PeerNotifications.PeerMessage.Authenticated parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(fishjam.PeerNotifications.PeerMessage.Authenticated prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Response sent by FJ, confirming successfull authentication
       * </pre>
       *
       * Protobuf type {@code fishjam.PeerMessage.Authenticated}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:fishjam.PeerMessage.Authenticated)
          fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_Authenticated_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_Authenticated_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fishjam.PeerNotifications.PeerMessage.Authenticated.class, fishjam.PeerNotifications.PeerMessage.Authenticated.Builder.class);
        }

        // Construct using fishjam.PeerNotifications.PeerMessage.Authenticated.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_Authenticated_descriptor;
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.Authenticated getDefaultInstanceForType() {
          return fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.Authenticated build() {
          fishjam.PeerNotifications.PeerMessage.Authenticated result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.Authenticated buildPartial() {
          fishjam.PeerNotifications.PeerMessage.Authenticated result = new fishjam.PeerNotifications.PeerMessage.Authenticated(this);
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fishjam.PeerNotifications.PeerMessage.Authenticated) {
            return mergeFrom((fishjam.PeerNotifications.PeerMessage.Authenticated)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fishjam.PeerNotifications.PeerMessage.Authenticated other) {
          if (other == fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }

        // @@protoc_insertion_point(builder_scope:fishjam.PeerMessage.Authenticated)
      }

      // @@protoc_insertion_point(class_scope:fishjam.PeerMessage.Authenticated)
      private static final fishjam.PeerNotifications.PeerMessage.Authenticated DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new fishjam.PeerNotifications.PeerMessage.Authenticated();
      }

      public static fishjam.PeerNotifications.PeerMessage.Authenticated getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Authenticated>
          PARSER = new com.google.protobuf.AbstractParser<Authenticated>() {
        @java.lang.Override
        public Authenticated parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Authenticated> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Authenticated> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.Authenticated getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface AuthRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fishjam.PeerMessage.AuthRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string token = 1;</code>
       * @return The token.
       */
      java.lang.String getToken();
      /**
       * <code>string token = 1;</code>
       * @return The bytes for token.
       */
      com.google.protobuf.ByteString
          getTokenBytes();
    }
    /**
     * <pre>
     * Request sent by peer, to authenticate to FJ server
     * </pre>
     *
     * Protobuf type {@code fishjam.PeerMessage.AuthRequest}
     */
    public static final class AuthRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:fishjam.PeerMessage.AuthRequest)
        AuthRequestOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          AuthRequest.class.getName());
      }
      // Use AuthRequest.newBuilder() to construct.
      private AuthRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private AuthRequest() {
        token_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_AuthRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_AuthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.PeerNotifications.PeerMessage.AuthRequest.class, fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder.class);
      }

      public static final int TOKEN_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       * @return The token.
       */
      @java.lang.Override
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        }
      }
      /**
       * <code>string token = 1;</code>
       * @return The bytes for token.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 1, token_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(1, token_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof fishjam.PeerNotifications.PeerMessage.AuthRequest)) {
          return super.equals(obj);
        }
        fishjam.PeerNotifications.PeerMessage.AuthRequest other = (fishjam.PeerNotifications.PeerMessage.AuthRequest) obj;

        if (!getToken()
            .equals(other.getToken())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static fishjam.PeerNotifications.PeerMessage.AuthRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(fishjam.PeerNotifications.PeerMessage.AuthRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Request sent by peer, to authenticate to FJ server
       * </pre>
       *
       * Protobuf type {@code fishjam.PeerMessage.AuthRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:fishjam.PeerMessage.AuthRequest)
          fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_AuthRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_AuthRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fishjam.PeerNotifications.PeerMessage.AuthRequest.class, fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder.class);
        }

        // Construct using fishjam.PeerNotifications.PeerMessage.AuthRequest.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          token_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_AuthRequest_descriptor;
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.AuthRequest getDefaultInstanceForType() {
          return fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.AuthRequest build() {
          fishjam.PeerNotifications.PeerMessage.AuthRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.AuthRequest buildPartial() {
          fishjam.PeerNotifications.PeerMessage.AuthRequest result = new fishjam.PeerNotifications.PeerMessage.AuthRequest(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(fishjam.PeerNotifications.PeerMessage.AuthRequest result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.token_ = token_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fishjam.PeerNotifications.PeerMessage.AuthRequest) {
            return mergeFrom((fishjam.PeerNotifications.PeerMessage.AuthRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fishjam.PeerNotifications.PeerMessage.AuthRequest other) {
          if (other == fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance()) return this;
          if (!other.getToken().isEmpty()) {
            token_ = other.token_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  token_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object token_ = "";
        /**
         * <code>string token = 1;</code>
         * @return The token.
         */
        public java.lang.String getToken() {
          java.lang.Object ref = token_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            token_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string token = 1;</code>
         * @return The bytes for token.
         */
        public com.google.protobuf.ByteString
            getTokenBytes() {
          java.lang.Object ref = token_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            token_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string token = 1;</code>
         * @param value The token to set.
         * @return This builder for chaining.
         */
        public Builder setToken(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          token_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string token = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearToken() {
          token_ = getDefaultInstance().getToken();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string token = 1;</code>
         * @param value The bytes for token to set.
         * @return This builder for chaining.
         */
        public Builder setTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          token_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:fishjam.PeerMessage.AuthRequest)
      }

      // @@protoc_insertion_point(class_scope:fishjam.PeerMessage.AuthRequest)
      private static final fishjam.PeerNotifications.PeerMessage.AuthRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new fishjam.PeerNotifications.PeerMessage.AuthRequest();
      }

      public static fishjam.PeerNotifications.PeerMessage.AuthRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<AuthRequest>
          PARSER = new com.google.protobuf.AbstractParser<AuthRequest>() {
        @java.lang.Override
        public AuthRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<AuthRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<AuthRequest> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.AuthRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface MediaEventOrBuilder extends
        // @@protoc_insertion_point(interface_extends:fishjam.PeerMessage.MediaEvent)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string data = 1;</code>
       * @return The data.
       */
      java.lang.String getData();
      /**
       * <code>string data = 1;</code>
       * @return The bytes for data.
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * <pre>
     * Any type of WebRTC messages passed betweend FJ and peer
     * </pre>
     *
     * Protobuf type {@code fishjam.PeerMessage.MediaEvent}
     */
    public static final class MediaEvent extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:fishjam.PeerMessage.MediaEvent)
        MediaEventOrBuilder {
    private static final long serialVersionUID = 0L;
      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 26,
          /* patch= */ 1,
          /* suffix= */ "",
          MediaEvent.class.getName());
      }
      // Use MediaEvent.newBuilder() to construct.
      private MediaEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private MediaEvent() {
        data_ = "";
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_MediaEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_MediaEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.PeerNotifications.PeerMessage.MediaEvent.class, fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder.class);
      }

      public static final int DATA_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object data_ = "";
      /**
       * <code>string data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        }
      }
      /**
       * <code>string data = 1;</code>
       * @return The bytes for data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 1, data_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(1, data_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof fishjam.PeerNotifications.PeerMessage.MediaEvent)) {
          return super.equals(obj);
        }
        fishjam.PeerNotifications.PeerMessage.MediaEvent other = (fishjam.PeerNotifications.PeerMessage.MediaEvent) obj;

        if (!getData()
            .equals(other.getData())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static fishjam.PeerNotifications.PeerMessage.MediaEvent parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(fishjam.PeerNotifications.PeerMessage.MediaEvent prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Any type of WebRTC messages passed betweend FJ and peer
       * </pre>
       *
       * Protobuf type {@code fishjam.PeerMessage.MediaEvent}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:fishjam.PeerMessage.MediaEvent)
          fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_MediaEvent_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_MediaEvent_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  fishjam.PeerNotifications.PeerMessage.MediaEvent.class, fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder.class);
        }

        // Construct using fishjam.PeerNotifications.PeerMessage.MediaEvent.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          data_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_MediaEvent_descriptor;
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.MediaEvent getDefaultInstanceForType() {
          return fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.MediaEvent build() {
          fishjam.PeerNotifications.PeerMessage.MediaEvent result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public fishjam.PeerNotifications.PeerMessage.MediaEvent buildPartial() {
          fishjam.PeerNotifications.PeerMessage.MediaEvent result = new fishjam.PeerNotifications.PeerMessage.MediaEvent(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(fishjam.PeerNotifications.PeerMessage.MediaEvent result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.data_ = data_;
          }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof fishjam.PeerNotifications.PeerMessage.MediaEvent) {
            return mergeFrom((fishjam.PeerNotifications.PeerMessage.MediaEvent)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(fishjam.PeerNotifications.PeerMessage.MediaEvent other) {
          if (other == fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance()) return this;
          if (!other.getData().isEmpty()) {
            data_ = other.data_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  data_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object data_ = "";
        /**
         * <code>string data = 1;</code>
         * @return The data.
         */
        public java.lang.String getData() {
          java.lang.Object ref = data_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            data_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string data = 1;</code>
         * @return The bytes for data.
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          java.lang.Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string data = 1;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          data_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string data = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          data_ = getDefaultInstance().getData();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string data = 1;</code>
         * @param value The bytes for data to set.
         * @return This builder for chaining.
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          data_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:fishjam.PeerMessage.MediaEvent)
      }

      // @@protoc_insertion_point(class_scope:fishjam.PeerMessage.MediaEvent)
      private static final fishjam.PeerNotifications.PeerMessage.MediaEvent DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new fishjam.PeerNotifications.PeerMessage.MediaEvent();
      }

      public static fishjam.PeerNotifications.PeerMessage.MediaEvent getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<MediaEvent>
          PARSER = new com.google.protobuf.AbstractParser<MediaEvent>() {
        @java.lang.Override
        public MediaEvent parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<MediaEvent> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<MediaEvent> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.MediaEvent getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int contentCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object content_;
    public enum ContentCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      AUTHENTICATED(1),
      AUTH_REQUEST(2),
      MEDIA_EVENT(3),
      CONTENT_NOT_SET(0);
      private final int value;
      private ContentCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ContentCase valueOf(int value) {
        return forNumber(value);
      }

      public static ContentCase forNumber(int value) {
        switch (value) {
          case 1: return AUTHENTICATED;
          case 2: return AUTH_REQUEST;
          case 3: return MEDIA_EVENT;
          case 0: return CONTENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ContentCase
    getContentCase() {
      return ContentCase.forNumber(
          contentCase_);
    }

    public static final int AUTHENTICATED_FIELD_NUMBER = 1;
    /**
     * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
     * @return Whether the authenticated field is set.
     */
    @java.lang.Override
    public boolean hasAuthenticated() {
      return contentCase_ == 1;
    }
    /**
     * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
     * @return The authenticated.
     */
    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage.Authenticated getAuthenticated() {
      if (contentCase_ == 1) {
         return (fishjam.PeerNotifications.PeerMessage.Authenticated) content_;
      }
      return fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
    }
    /**
     * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
     */
    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder getAuthenticatedOrBuilder() {
      if (contentCase_ == 1) {
         return (fishjam.PeerNotifications.PeerMessage.Authenticated) content_;
      }
      return fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
    }

    public static final int AUTH_REQUEST_FIELD_NUMBER = 2;
    /**
     * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
     * @return Whether the authRequest field is set.
     */
    @java.lang.Override
    public boolean hasAuthRequest() {
      return contentCase_ == 2;
    }
    /**
     * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
     * @return The authRequest.
     */
    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage.AuthRequest getAuthRequest() {
      if (contentCase_ == 2) {
         return (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_;
      }
      return fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
    }
    /**
     * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
     */
    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder getAuthRequestOrBuilder() {
      if (contentCase_ == 2) {
         return (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_;
      }
      return fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
    }

    public static final int MEDIA_EVENT_FIELD_NUMBER = 3;
    /**
     * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
     * @return Whether the mediaEvent field is set.
     */
    @java.lang.Override
    public boolean hasMediaEvent() {
      return contentCase_ == 3;
    }
    /**
     * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
     * @return The mediaEvent.
     */
    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage.MediaEvent getMediaEvent() {
      if (contentCase_ == 3) {
         return (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_;
      }
      return fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
    }
    /**
     * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
     */
    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder getMediaEventOrBuilder() {
      if (contentCase_ == 3) {
         return (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_;
      }
      return fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (contentCase_ == 1) {
        output.writeMessage(1, (fishjam.PeerNotifications.PeerMessage.Authenticated) content_);
      }
      if (contentCase_ == 2) {
        output.writeMessage(2, (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_);
      }
      if (contentCase_ == 3) {
        output.writeMessage(3, (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contentCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (fishjam.PeerNotifications.PeerMessage.Authenticated) content_);
      }
      if (contentCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_);
      }
      if (contentCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fishjam.PeerNotifications.PeerMessage)) {
        return super.equals(obj);
      }
      fishjam.PeerNotifications.PeerMessage other = (fishjam.PeerNotifications.PeerMessage) obj;

      if (!getContentCase().equals(other.getContentCase())) return false;
      switch (contentCase_) {
        case 1:
          if (!getAuthenticated()
              .equals(other.getAuthenticated())) return false;
          break;
        case 2:
          if (!getAuthRequest()
              .equals(other.getAuthRequest())) return false;
          break;
        case 3:
          if (!getMediaEvent()
              .equals(other.getMediaEvent())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (contentCase_) {
        case 1:
          hash = (37 * hash) + AUTHENTICATED_FIELD_NUMBER;
          hash = (53 * hash) + getAuthenticated().hashCode();
          break;
        case 2:
          hash = (37 * hash) + AUTH_REQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getAuthRequest().hashCode();
          break;
        case 3:
          hash = (37 * hash) + MEDIA_EVENT_FIELD_NUMBER;
          hash = (53 * hash) + getMediaEvent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fishjam.PeerNotifications.PeerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fishjam.PeerNotifications.PeerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fishjam.PeerNotifications.PeerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fishjam.PeerNotifications.PeerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Defines any type of message sent between FJ and a peer
     * </pre>
     *
     * Protobuf type {@code fishjam.PeerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fishjam.PeerMessage)
        fishjam.PeerNotifications.PeerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fishjam.PeerNotifications.PeerMessage.class, fishjam.PeerNotifications.PeerMessage.Builder.class);
      }

      // Construct using fishjam.PeerNotifications.PeerMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (authenticatedBuilder_ != null) {
          authenticatedBuilder_.clear();
        }
        if (authRequestBuilder_ != null) {
          authRequestBuilder_.clear();
        }
        if (mediaEventBuilder_ != null) {
          mediaEventBuilder_.clear();
        }
        contentCase_ = 0;
        content_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fishjam.PeerNotifications.internal_static_fishjam_PeerMessage_descriptor;
      }

      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage getDefaultInstanceForType() {
        return fishjam.PeerNotifications.PeerMessage.getDefaultInstance();
      }

      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage build() {
        fishjam.PeerNotifications.PeerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage buildPartial() {
        fishjam.PeerNotifications.PeerMessage result = new fishjam.PeerNotifications.PeerMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(fishjam.PeerNotifications.PeerMessage result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(fishjam.PeerNotifications.PeerMessage result) {
        result.contentCase_ = contentCase_;
        result.content_ = this.content_;
        if (contentCase_ == 1 &&
            authenticatedBuilder_ != null) {
          result.content_ = authenticatedBuilder_.build();
        }
        if (contentCase_ == 2 &&
            authRequestBuilder_ != null) {
          result.content_ = authRequestBuilder_.build();
        }
        if (contentCase_ == 3 &&
            mediaEventBuilder_ != null) {
          result.content_ = mediaEventBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fishjam.PeerNotifications.PeerMessage) {
          return mergeFrom((fishjam.PeerNotifications.PeerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fishjam.PeerNotifications.PeerMessage other) {
        if (other == fishjam.PeerNotifications.PeerMessage.getDefaultInstance()) return this;
        switch (other.getContentCase()) {
          case AUTHENTICATED: {
            mergeAuthenticated(other.getAuthenticated());
            break;
          }
          case AUTH_REQUEST: {
            mergeAuthRequest(other.getAuthRequest());
            break;
          }
          case MEDIA_EVENT: {
            mergeMediaEvent(other.getMediaEvent());
            break;
          }
          case CONTENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAuthenticatedFieldBuilder().getBuilder(),
                    extensionRegistry);
                contentCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getAuthRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                contentCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getMediaEventFieldBuilder().getBuilder(),
                    extensionRegistry);
                contentCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int contentCase_ = 0;
      private java.lang.Object content_;
      public ContentCase
          getContentCase() {
        return ContentCase.forNumber(
            contentCase_);
      }

      public Builder clearContent() {
        contentCase_ = 0;
        content_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          fishjam.PeerNotifications.PeerMessage.Authenticated, fishjam.PeerNotifications.PeerMessage.Authenticated.Builder, fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder> authenticatedBuilder_;
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       * @return Whether the authenticated field is set.
       */
      @java.lang.Override
      public boolean hasAuthenticated() {
        return contentCase_ == 1;
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       * @return The authenticated.
       */
      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.Authenticated getAuthenticated() {
        if (authenticatedBuilder_ == null) {
          if (contentCase_ == 1) {
            return (fishjam.PeerNotifications.PeerMessage.Authenticated) content_;
          }
          return fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
        } else {
          if (contentCase_ == 1) {
            return authenticatedBuilder_.getMessage();
          }
          return fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
        }
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      public Builder setAuthenticated(fishjam.PeerNotifications.PeerMessage.Authenticated value) {
        if (authenticatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          authenticatedBuilder_.setMessage(value);
        }
        contentCase_ = 1;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      public Builder setAuthenticated(
          fishjam.PeerNotifications.PeerMessage.Authenticated.Builder builderForValue) {
        if (authenticatedBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          authenticatedBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 1;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      public Builder mergeAuthenticated(fishjam.PeerNotifications.PeerMessage.Authenticated value) {
        if (authenticatedBuilder_ == null) {
          if (contentCase_ == 1 &&
              content_ != fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance()) {
            content_ = fishjam.PeerNotifications.PeerMessage.Authenticated.newBuilder((fishjam.PeerNotifications.PeerMessage.Authenticated) content_)
                .mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 1) {
            authenticatedBuilder_.mergeFrom(value);
          } else {
            authenticatedBuilder_.setMessage(value);
          }
        }
        contentCase_ = 1;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      public Builder clearAuthenticated() {
        if (authenticatedBuilder_ == null) {
          if (contentCase_ == 1) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 1) {
            contentCase_ = 0;
            content_ = null;
          }
          authenticatedBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      public fishjam.PeerNotifications.PeerMessage.Authenticated.Builder getAuthenticatedBuilder() {
        return getAuthenticatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder getAuthenticatedOrBuilder() {
        if ((contentCase_ == 1) && (authenticatedBuilder_ != null)) {
          return authenticatedBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 1) {
            return (fishjam.PeerNotifications.PeerMessage.Authenticated) content_;
          }
          return fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
        }
      }
      /**
       * <code>.fishjam.PeerMessage.Authenticated authenticated = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          fishjam.PeerNotifications.PeerMessage.Authenticated, fishjam.PeerNotifications.PeerMessage.Authenticated.Builder, fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder> 
          getAuthenticatedFieldBuilder() {
        if (authenticatedBuilder_ == null) {
          if (!(contentCase_ == 1)) {
            content_ = fishjam.PeerNotifications.PeerMessage.Authenticated.getDefaultInstance();
          }
          authenticatedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              fishjam.PeerNotifications.PeerMessage.Authenticated, fishjam.PeerNotifications.PeerMessage.Authenticated.Builder, fishjam.PeerNotifications.PeerMessage.AuthenticatedOrBuilder>(
                  (fishjam.PeerNotifications.PeerMessage.Authenticated) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 1;
        onChanged();
        return authenticatedBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          fishjam.PeerNotifications.PeerMessage.AuthRequest, fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder, fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder> authRequestBuilder_;
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       * @return Whether the authRequest field is set.
       */
      @java.lang.Override
      public boolean hasAuthRequest() {
        return contentCase_ == 2;
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       * @return The authRequest.
       */
      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.AuthRequest getAuthRequest() {
        if (authRequestBuilder_ == null) {
          if (contentCase_ == 2) {
            return (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_;
          }
          return fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
        } else {
          if (contentCase_ == 2) {
            return authRequestBuilder_.getMessage();
          }
          return fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      public Builder setAuthRequest(fishjam.PeerNotifications.PeerMessage.AuthRequest value) {
        if (authRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          authRequestBuilder_.setMessage(value);
        }
        contentCase_ = 2;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      public Builder setAuthRequest(
          fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder builderForValue) {
        if (authRequestBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          authRequestBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 2;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      public Builder mergeAuthRequest(fishjam.PeerNotifications.PeerMessage.AuthRequest value) {
        if (authRequestBuilder_ == null) {
          if (contentCase_ == 2 &&
              content_ != fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance()) {
            content_ = fishjam.PeerNotifications.PeerMessage.AuthRequest.newBuilder((fishjam.PeerNotifications.PeerMessage.AuthRequest) content_)
                .mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 2) {
            authRequestBuilder_.mergeFrom(value);
          } else {
            authRequestBuilder_.setMessage(value);
          }
        }
        contentCase_ = 2;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      public Builder clearAuthRequest() {
        if (authRequestBuilder_ == null) {
          if (contentCase_ == 2) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 2) {
            contentCase_ = 0;
            content_ = null;
          }
          authRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      public fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder getAuthRequestBuilder() {
        return getAuthRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder getAuthRequestOrBuilder() {
        if ((contentCase_ == 2) && (authRequestBuilder_ != null)) {
          return authRequestBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 2) {
            return (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_;
          }
          return fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.fishjam.PeerMessage.AuthRequest auth_request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          fishjam.PeerNotifications.PeerMessage.AuthRequest, fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder, fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder> 
          getAuthRequestFieldBuilder() {
        if (authRequestBuilder_ == null) {
          if (!(contentCase_ == 2)) {
            content_ = fishjam.PeerNotifications.PeerMessage.AuthRequest.getDefaultInstance();
          }
          authRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              fishjam.PeerNotifications.PeerMessage.AuthRequest, fishjam.PeerNotifications.PeerMessage.AuthRequest.Builder, fishjam.PeerNotifications.PeerMessage.AuthRequestOrBuilder>(
                  (fishjam.PeerNotifications.PeerMessage.AuthRequest) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 2;
        onChanged();
        return authRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          fishjam.PeerNotifications.PeerMessage.MediaEvent, fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder, fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder> mediaEventBuilder_;
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       * @return Whether the mediaEvent field is set.
       */
      @java.lang.Override
      public boolean hasMediaEvent() {
        return contentCase_ == 3;
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       * @return The mediaEvent.
       */
      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.MediaEvent getMediaEvent() {
        if (mediaEventBuilder_ == null) {
          if (contentCase_ == 3) {
            return (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_;
          }
          return fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
        } else {
          if (contentCase_ == 3) {
            return mediaEventBuilder_.getMessage();
          }
          return fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      public Builder setMediaEvent(fishjam.PeerNotifications.PeerMessage.MediaEvent value) {
        if (mediaEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          mediaEventBuilder_.setMessage(value);
        }
        contentCase_ = 3;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      public Builder setMediaEvent(
          fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder builderForValue) {
        if (mediaEventBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          mediaEventBuilder_.setMessage(builderForValue.build());
        }
        contentCase_ = 3;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      public Builder mergeMediaEvent(fishjam.PeerNotifications.PeerMessage.MediaEvent value) {
        if (mediaEventBuilder_ == null) {
          if (contentCase_ == 3 &&
              content_ != fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance()) {
            content_ = fishjam.PeerNotifications.PeerMessage.MediaEvent.newBuilder((fishjam.PeerNotifications.PeerMessage.MediaEvent) content_)
                .mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          if (contentCase_ == 3) {
            mediaEventBuilder_.mergeFrom(value);
          } else {
            mediaEventBuilder_.setMessage(value);
          }
        }
        contentCase_ = 3;
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      public Builder clearMediaEvent() {
        if (mediaEventBuilder_ == null) {
          if (contentCase_ == 3) {
            contentCase_ = 0;
            content_ = null;
            onChanged();
          }
        } else {
          if (contentCase_ == 3) {
            contentCase_ = 0;
            content_ = null;
          }
          mediaEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      public fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder getMediaEventBuilder() {
        return getMediaEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      @java.lang.Override
      public fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder getMediaEventOrBuilder() {
        if ((contentCase_ == 3) && (mediaEventBuilder_ != null)) {
          return mediaEventBuilder_.getMessageOrBuilder();
        } else {
          if (contentCase_ == 3) {
            return (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_;
          }
          return fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.fishjam.PeerMessage.MediaEvent media_event = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          fishjam.PeerNotifications.PeerMessage.MediaEvent, fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder, fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder> 
          getMediaEventFieldBuilder() {
        if (mediaEventBuilder_ == null) {
          if (!(contentCase_ == 3)) {
            content_ = fishjam.PeerNotifications.PeerMessage.MediaEvent.getDefaultInstance();
          }
          mediaEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              fishjam.PeerNotifications.PeerMessage.MediaEvent, fishjam.PeerNotifications.PeerMessage.MediaEvent.Builder, fishjam.PeerNotifications.PeerMessage.MediaEventOrBuilder>(
                  (fishjam.PeerNotifications.PeerMessage.MediaEvent) content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        contentCase_ = 3;
        onChanged();
        return mediaEventBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:fishjam.PeerMessage)
    }

    // @@protoc_insertion_point(class_scope:fishjam.PeerMessage)
    private static final fishjam.PeerNotifications.PeerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fishjam.PeerNotifications.PeerMessage();
    }

    public static fishjam.PeerNotifications.PeerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PeerMessage>
        PARSER = new com.google.protobuf.AbstractParser<PeerMessage>() {
      @java.lang.Override
      public PeerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PeerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeerMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fishjam.PeerNotifications.PeerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_PeerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_PeerMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_PeerMessage_Authenticated_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_PeerMessage_Authenticated_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_PeerMessage_AuthRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_PeerMessage_AuthRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fishjam_PeerMessage_MediaEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fishjam_PeerMessage_MediaEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n fishjam/peer_notifications.proto\022\007fish" +
      "jam\"\222\002\n\013PeerMessage\022;\n\rauthenticated\030\001 \001" +
      "(\0132\".fishjam.PeerMessage.AuthenticatedH\000" +
      "\0228\n\014auth_request\030\002 \001(\0132 .fishjam.PeerMes" +
      "sage.AuthRequestH\000\0226\n\013media_event\030\003 \001(\0132" +
      "\037.fishjam.PeerMessage.MediaEventH\000\032\017\n\rAu" +
      "thenticated\032\034\n\013AuthRequest\022\r\n\005token\030\001 \001(" +
      "\t\032\032\n\nMediaEvent\022\014\n\004data\030\001 \001(\tB\t\n\007content" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fishjam_PeerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fishjam_PeerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_PeerMessage_descriptor,
        new java.lang.String[] { "Authenticated", "AuthRequest", "MediaEvent", "Content", });
    internal_static_fishjam_PeerMessage_Authenticated_descriptor =
      internal_static_fishjam_PeerMessage_descriptor.getNestedTypes().get(0);
    internal_static_fishjam_PeerMessage_Authenticated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_PeerMessage_Authenticated_descriptor,
        new java.lang.String[] { });
    internal_static_fishjam_PeerMessage_AuthRequest_descriptor =
      internal_static_fishjam_PeerMessage_descriptor.getNestedTypes().get(1);
    internal_static_fishjam_PeerMessage_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_PeerMessage_AuthRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_fishjam_PeerMessage_MediaEvent_descriptor =
      internal_static_fishjam_PeerMessage_descriptor.getNestedTypes().get(2);
    internal_static_fishjam_PeerMessage_MediaEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fishjam_PeerMessage_MediaEvent_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
