// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: fishjam/peer_notifications.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

package fishjam
